spring.application.name=GrievanceTracker

# 🐘 PostgreSQL Database Connection
# PASTE YOUR NEON JDBC LINK ON THE LINE BELOW:
spring.datasource.url=jdbc:postgresql://ep-royal-leaf-azdhlk9k-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_h5F2avKeXNxw&sslmode=require&channelBinding=require

# Hibernate configurations (Translates Java code into PostgreSQL tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect